language: emacs-lisp

env:
  global:
    - PATH=$HOME/.evm/bin:$HOME/.cask/bin:$PATH

before_install:
  - sudo apt-add-repository -y ppa:ansible/ansible
  - sudo apt-get update
  - sudo apt-get install -y ansible

install:
  - ./travis.sh

script:
  - ./ert.sh
