language: emacs-lisp
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.pyenv
    - $HOME/.evm
    - $HOME/.cask
    - $TRAVIS_BUILD_DIR/.cask
    - $TRAVIS_BUILD_DIR/.tox
    - /usr/local/evm
env:
  global:
    - PATH=$HOME/.evm/bin:$HOME/.cask/bin:$PATH
before_install:
  - sudo apt-add-repository -y ppa:ansible/ansible
  - sudo apt-get update
  - sudo apt-get install -y ansible
install:
  - ./travis.sh
script:
  - ./ert.sh
