- name: create ssh directory for test user
  file: dest=/home/test/.ssh state=directory
  become: yes
  become_user: test
- name: create authorized keys file for test user
  file: dest=/home/test/.ssh/authorized_keys state=touch
  become: yes
  become_user: test
- name: cat generated ssh key
  command: cat {{ ansible_env.HOME }}/.ssh/id_rsa.pub
  register: id_rsa
- name: register generated key
  lineinfile: dest=/home/test/.ssh/authorized_keys line="{{ id_rsa.stdout }}"
  become: yes
  become_user: test
