- name: install evm
  git: repo=https://github.com/rejeep/evm dest=~/.evm
- name: create evm directory
  file: dest=/usr/local/evm state=directory mode=0777
  become: yes
- name: install emacs
  command: evm install {{ ansible_env.EMACS_VERSION }}
- name: use emacs
  command: evm use {{ ansible_env.EMACS_VERSION }}
